GET http://localhost:5000/api/phone?page=1&results=5

# 404
GET http://localhost:5000/api/phone?page=f&results=s


GET http://localhost:5000/api/phone/4

# 404
GET http://localhost:5000/api/phone/1000


POST http://localhost:5000/api/phone
Content-Type: application/json

{
  "model": "18d",
  "brand": "OnePlus",
  "yearProduction": "2024-01-01",
  "sizeRam": "3 GB",
  "cpu": "Snapdragon 8 Gen 2",
  "screenDiagonal": "6.78",
  "isNfc": true
}

# 500
POST http://localhost:5000/api/phone
Content-Type: application/json

{
  "model": "1",
  "brand": "OnePlus",
  "yearProduction": "2024-01-01",
  "sizeRam": "3 GB",
  "cpu": "Snapdragon 8 Gen 2"
}



PATCH http://localhost:5000/api/phone/2
Content-Type: application/json

{
  "model": "17A",
  "brand": "Samsung",
  "yearProduction": "2025-01-01",
  "sizeRam": "8 GB",
  "cpu": "Snapdragon 8 Gen 2",
  "screenDiagonal": "6.3",
  "isNfc": true
}

# 422
PATCH http://localhost:5000/api/phone/2
Content-Type: application/json

{
  "isNfc": 45
}

DELETE http://localhost:5000/api/phone/7

# 404
DELETE http://localhost:5000/api/phone/1000
